cfg_data:
  ...

cfg_train:
  n_epoch: 100 # Total number of epochs
  n_tb_epoch: 100 # Total number of training batches per epoch
  device: 'gpu' # Device used
  dtype: 'float32' # Dtype used

cfg_export:
  project: 'Testing Synthetic Data - 1D Cond-UNet'
  name: '1st Test Run'
  model_save: 'cond_unet.pth' # The save path for the model (critic) that was trained, can have .pth, adds it automatically
  test_save: 'preds.parquet' # Save path for the predictions on test data
  local_log: 'test_logs.txt' # Path for the local loggging of alerts prints, etc
  
cfg_critic_setup:

  critic_type: 'MLP' # The type of critic to be trained
  cfg_critic: # Specific configs of the critic
    ... 

cfg_optim_setup:

  loss_type: 'MSE' # The name of loss function to train critic
  cfg_loss: # Configs to initialize the loss function
    ...

  cfg_optim_type: 'AdamW'
  cfg_optim:
    lr: 1e-3
    weight_decay: 1e-2
    cfg_lrscheduler_setup: # If this is not given, lr scheduler will default to None
      lrscheduler_type: 'CosineAnealingLR'
      cfg_lrscheduler:
        ...

