cfg_synthesis:
  n_targets: 47 # The total amount of 'target_size's to be generated, i.e. final dataset shape: (n_targets * Batch, n_bands)
  norm_dict_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\synthesis\diffusion\pipeline_test\norm_dict.json' # The path (...json) that has the dict storing how normalization was conducted
  architecture: GaussianDiffusion # The main class representing model architecture e.g.: GaussianDiffusion (in the diffusion code)
  cfg_model_setup_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\synthesis\diffusion\pipeline_test\cfg_diffusion_setup.json' # The path to the model dict, for diffusion this would be cfg_diffusion_setup.json outputted after diffusion training
  model_statedict_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\synthesis\diffusion\pipeline_test\diffusion_model.pth' # The path for the model's statedict
  device: 'cuda' # The preferred device to conduct data synthesis on

  cfg_absampler_setup:
    absampler_type: 'UniAbSamp'
    cfg_absampler: # We do not include device here, it will be passed in at the config functions
      target_shape: [32,3] # Format is: [Batch, n_endmembers]
      seed: 3169 # Random seed for reproducibility

cfg_export:
  entity: 'UTAT-Science' # The team entity name
  project: 'Data Synthesis' # Project name
  name: 'Pipeline Test 2' # Run name
  master_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\synthesis\diffusion\test_pipeline_test\' # Master save path of the folder we are running everything in (must end with '\')
  ksi_train_path: 'ksi_train.csv' # This is the rest of the path that will be used to save the generated CSV
  locallog_save:  'logs.txt' # Save path of the local log
  naming_base: 'CUNet_v01' # Some base naming convention that'll be used to name all the spectra
  spectral_range: [400, 2490] # The spectral range of the data to be synthesized, used for CSV header generation

