cfg_data:
  cfg_import:
    data_handle: '/data/simpler_data_rwc.csv' # Path for the data file
    spec_range: [400, 2490] # Spectral range, inclusive

  cfg_normalize:
    norm_type: 'none' # Options are classic, dynamic, log, none. Normalizes data

  cfg_loader:
    n_val: 100 # Number of val points used at each epoch, we use a static validation set (i.e. use the same val set each epoch)
    n_test: 123 # Number of test points at the end of training
    n_train_batch: 1 # The training batch size
    seed: 1001 # Seed for the data splitters

  cfg_split: # Train/val split data
    split_ratio: 0.8
    batch_size: 1
  
  cfg_dataset_save:
    psi1_path: "defs/vae/psi_1" # Save path for the psi1 dataset do not have .csv after this since it adds the norm methods before .csv
    psi2_path: "defs/vae/psi_2" # Save path for the psi2 dataset do not have .csv after this since it adds the norm methods before .csv 

cfg_train: 
  n_epoch: 50 # Number of training epochs
  n_tb_epoch: 100 # Number of training instances/batches, will have this many batches in training
  device: 'cpu' # Device to be used
  dtype: 'float32' # Datatype to be used
  
cfg_export:
  entity: 'cshuo777-university-of-toronto' # The team entity name
  project: 'VCCAE Synthetic Data Generation'
  name: 'train_001-3'
  model_save: 'vccae_model.pth' # The save path for the model that was trained, can have .pth, adds it automatically
  test_save: 'generated_test_samples.parquet' # Save path for the generated test samples
  norm_save: 'norm_dict.json'
  master_path: ''
  modelinits_save: 'vccae_model_inits.json' # Path to save the model initial config
  local_log: 'test_logs.txt' # Path for the local logging of alerts prints, etc
  locallog_save: 'test_logs.txt' # Path for the local logging of alerts prints, etc (bruh)
  psi1_path: "psi1.pth"
  psi2_path: "psi2.pth"
  save_to_wandb: True # Whether to save everything to wandb

cfg_ae_setup:
  ae_type: 'VCCAE' # The name of the encoder class
  cfg_ae:
    conv_layers: [1, 256, 256, 256, 256]
    mlp_layers: [256, 256, 256, 256]
    num_spectra: 210
    out_layer: 64
    c_d: {'pad': 1} # Convolution details
    ab_mlp: [3, 128, 128, 128]
    # compressed_sampling: False
    # dynamicthresh_sampling: True
    # sampling_method: 'ddim'
    # temperature: 0.8
    # guidance_scale: 3.0
    # uncond_prob: 0.1
    # ema_decay: 0.999
    # ddim_steps: 50
  # The rest of specific configs of the diffusion get built in the script

# cfg_epsilon_setup: 
#   epsilon_type: 'Epsilon_Cond1DUnet'
#   cfg_epsilon:
#     ... # The specific configs for the epsilon

# cfg_augmenter_setup:
#   augmenter_type: 'SpectralAugmentation' # Name of the augmenter class
#   cfg_augmenter:
#     seed: 3169
#     jitter_scale: 1.0e-4
#     amp_scale: 1.0e-2

cfg_scheduler_setup:
  scheduler_type: 'CosSchedule' # Name of the noise scheduler class
  cfg_scheduler:
    steps: 3000 # Usually same as the tmax of tsampler, doesn't have to be if want to limit the max t during training
    offset: 8.0e-3
    exp: 2

# cfg_tsampler_setup:
#   tsampler_type: 'NormalSampling'
#   cfg_tsampler: 
#     t_max: 3000 # Usually same as the steps of scheduler, doesn't have to be if want to limit the max t during training
#     t_min: 0  

cfg_optim_setup:
  optim_type: 'Adam'
  cfg_optim:
    lr: 1.0e-5
    weight_decay: 1.0e-2
    cfg_lrscheduler_setup: # If this is not given, lr scheduler will default to None
      lrscheduler_type: 'CosineAnealingLR'
      cfg_lrscheduler:
        ...

cfg_loss_setup:
  loss_type: 'LossKLSAM' 
  # cfg_loss:
    # noise_loss_type: 'huber'
    # use_recons_loss: 'observe'
  