model:
  loss_name: scale_vae
  lr: 0.0001
  loss_params:
    des_std: 1.0
    f_epo: 10
    scale_eps: 1.0e-6
    recon: mse
    masked_wavelength_ranges_nm:
      - [1700, 1900]
    masked_wavelength_weight: 0.1
    wavelength_start_nm: 400
    wavelength_step_nm: 10
