cfg_export:
  entity: 'UTAT-Science'
  project: 'Testing Synthetic Data - 1D Cond-UNet'
  name: 'Validating Test Pipeline'
  local_log: 'test_logs.txt' # Path for the local loggging of alerts prints, etc
  
cfg_unmix:

  cfg_import:
    ksi_train_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\synthesis\diffusion\test_pipeline_test\ksi_train.csv' # The exact path of the .csv for the generated dataset, that will be used to train the critic
    psi2_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\training\diffusion\ExpAnalysis_002-0\psi2.csv' # The exact path for the psi_2/ksi_val+ksi_tests dataset, which is the dataset NOT used to train the synthesizer, only used in val/test
    norm_dict_path: 'training/diffusion/ExpAnalysis_002-0/norm_dict.json' # The path (...json) that has the dict storing how normalization was conducted
    spec_range: [400, 2490] # Spectral range, inclusive

  cfg_loader:
    n_val: 100 # Number of val datapoints in ksi_val
    n_test: 123 # Number of test datapoints in ksi_val
    n_train_batch: 16 # Size of training batches in ksi_train
    num_workers: 4 # Number of workers in train loader
    prefetch_factor: 12 # How many batches each worker will prefetch
    seed: 3169 # Seed to seperate val and test in ksi_val

  cfg_train:  
    n_epoch: 10 # Total number of epochs
    n_tb_epoch: 94 # Total number of training batches per epoch
    device: 'cuda' # Device used
    dtype: 'float32' # Dtype used
    verbose: True # If want to output all the losses
    use_autocast: False # If want to use autocast (float16) to speed up calcs

  cfg_export:
    model_save: 'mlp.pth' # The save path for the model (critic) that was trained, can have .pth, adds it automatically
    test_save: 'preds.parquet' # Save path for the predictions on test data
    
  cfg_critic_setup:
    critic_type: 'MLP' # The type of critic to be trained
    cfg_critic: # Specific configs of the critic
      input_size: 210 # The input size of the critic, should match the spectral length of the data
      hidden_sizes: [256,256,256,128] # The hidden layer sizes of the MLP critic
      output_size: 3 # The output size of the critic, usually 1 for a regression task
      activation: 'silu' # The activation function to be used between layers 

  cfg_optim_setup:
    loss_type: 'MSE' # The name of loss function to train critic
    cfg_loss: # Configs to initialize the loss function
    cfg_optim_type: 'AdamW'
    cfg_optim:
      lr: 1e-3
      weight_decay: 1e-2
      cfg_lrscheduler_setup: # If this is not given, lr scheduler will default to None
        lrscheduler_type: 'CosineAnnealingLR'
        cfg_lrscheduler:
          T_max: 10
cfg_nearneigh:

  cfg_import:
    psi2_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\training\diffusion\ExpAnalysis_002-0\psi2.csv' # The exact path for the psi_2/ksi_val+ksi_tests dataset, which is the dataset NOT used to train the synthesizer, only used in val/test
    spec_range: [400, 2490] # Spectral range, inclusive, will be used to synthesize the data, has to match the trained model specs
    separation_ratio: 0.5 # The exact separation ratio for the data to be synthesized and preserved, # of real = sep_ratio * len(dataset)

  # Specifics of synthesis
  cfg_synthesis:
    model_type: GaussianDiffusion # The main class representing model architecture/type e.g.: GaussianDiffusion (in the diffusion code)
    cfg_model_setup_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\training\diffusion\ExpAnalysis_002-0\cfg_diffusion_setup.json' # The path to the model dict, for diffusion this would be cfg_diffusion_setup.json outputted after diffusion training
    model_statedict_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\training\diffusion\ExpAnalysis_002-0\diffusion_model.pth' # The path for the model's statedict
    norm_dict_path: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\training\diffusion\ExpAnalysis_002-0\norm_dict.json' # The path for the norm dict used during training, needed for proper denormalization
    max_batch_size: 50 # The maximum batch size to be used during synthesis of points, usually safe to max out, any number more than the actual size defaults to the actual size, hard capped at 32
    device: 'cuda'

  # The omega, each element is a dict of args
  cfg_omega: 
    omega_1: 
      type: 'euc'
      method: 'min'
      spec_idx: [0,210]
      p: 2
    omega_2:
      type: 'sam'
      method: 'min'
      spec_idx: [0,210]
    omega_3:
      type: 'euc'
      method: 'max'
      spec_idx: [0,210]
      p: 5
    omega_4:
      type: 'sam'
      method: 'max'
      spec_idx: [0,210]
  
  cfg_export:
    metrics_save: 'C:\SenkDosya\Projects\FINCH-Science_SyntheticData\testing\diffusion\pipeline_test\metric_save.csv' # The save path for the metric results

  # Details on plotting the blobs, unused for now
  #cfg_blobs: ...
